Add typing for the Dict prop access
j2inn/haystack-core pull request #19
Opened 2022-11-12 01:45 UTC by rracariu

Proposing this feature so one could safely use the proxy access pattern in TypeScript code.

2022-11-12 08:33 UTC, garethj2 requested changes
Really not sure about this change. See comments.

2022-11-12 08:33 UTC, garethj2 commented on src/core/HDict.ts
> +	readonly [prop: string]: unknown | undefined
I'm unsure about this change since it opens up dynamic property access that's usually handled by HDict interfaces.

For instance, if we have...

```
class Foo extends HDict {
  bar?: HStr
}

...
const foo = new HDict() as Foo

foo.bar = HStr.make('this is a type')
```

With this change, I could accidently do this...

```
foo.barr = HStr.make('this is a type')
```

I think it would be best to try and avoid this scenario but using the HDict interface types.

Not only that, this opens up potential problems when someone accidently types in an incorrect method name hence resulting in a possible runtime error.

What do you think?

2022-11-12 08:49 UTC, garethj2 requested changes

2022-11-12 08:49 UTC, garethj2 commented on src/core/HDict.ts
> +	readonly [prop: string]: unknown | undefined
I'm unsure about this change since it could lead to some errors...

```
interface Foo extends HDict {
  bar?: HStr
}

const foo = new HDict() as Foo

// Made a mistake but there's no compilier error.
const value = foo.barr
```

2022-11-14 17:22 UTC, rracariu commented on src/core/HDict.ts
> +	readonly [prop: string]: unknown | undefined
Usually you would assign or pass on that value to other functions, given that property access is always `unknown` you would be forced to always cast it away.

On this example, considering the code
```
const value  = foo.barr
value.inspect() // error: Object is of type 'unknown'
```

Or
```
const value: HStr = fooDict.barr // Type 'unknown' is not assignable to type 'HStr'
```

2022-11-14 17:28 UTC, rracariu commented on src/core/HDict.ts
> +	readonly [prop: string]: unknown | undefined
I don't see this as a loos as it still covers the type safe access pattern with the interface definitions, but at the same time will make `HDict` behavior consistent with how you would use it in JavaScript.

2022-11-14 18:14 UTC, garethj2 commented on src/core/HDict.ts
> +	readonly [prop: string]: unknown | undefined
I agree it makes it more consistent with JavaScript. I think most people will probably get the casting wrong and use this...

```
const value: HStr = fooDict.barr
```

When they should probably be casting like this...

```
const value: HStr | undefined = fooDict.barr

if (value) {
  ...
}
```

Again one could argue this is required in the interface anyway. 

When refactoring with interfaces (let's say I change something), I normally like it to be fairly explicit rather than returned to a casting error. I think this makes it less confusing for a developer.

You make good points but I still find myself on the fence about this one. I'm happy to go with the majority.

I'd really appreciate other opinions on this @shal1y , @J2Rochelle , @thoughtpalette , @EliteScientist , @hecsalazarf .

2022-11-15 01:56 UTC, EliteScientist commented on src/core/HDict.ts
> +	readonly [prop: string]: unknown | undefined
I have this same exact issue with the Graphics Builder right now. I actually have to have {[key:string]: unkown] in the parent component type because it allows any tag to be added to a component and serialized. This is how a lot of the graphics builder functions so I can't change it.

Now when it comes to a class extending FINComponent. I've ran into issues while testing where I make a typo calling a function or accessing a property and the compiler or IDE doesn't catch it.

Now I definitely see the need that Radu mentioned. It would be nice if there was a way to display warnings when members are accessed and do not exist in the interface/class.

2022-11-16 15:44 UTC, hecsalazarf commented on src/core/HDict.ts
> +	readonly [prop: string]: unknown | undefined
I think both perspectives are valid. Although you would be forced to cast, it's still prone to empty values if the developer isn't careful enough. I wouldn't worry too much, however, If we really wanted to eradicate errors,  a `Maybe` monad could be implemented.

2022-11-22 17:10 UTC, garethj2 commented on src/core/HDict.ts
> +	readonly [prop: string]: unknown | undefined
Thanks for all the comments everyone. I'm getting the impression that everyone sees both sides but overall favours the change.

2022-11-22 17:11 UTC, garethj2 approved these changes

2022-11-22 17:11 UTC, merged