Created ability to expire memoization.
j2inn/haystack-core pull request #7
Opened 2022-05-28 03:26 UTC by EliteScientist

2022-05-29 08:53 UTC, garethj2 requested changes

2022-05-29 08:53 UTC, garethj2 commented on src/util/memoize.ts
> +	public expire(name?: string): void {
I think the word expire is synonymous with something that is time related. At some point, I think we really could add something that automatically clears entries after a time delay!

Therefore something like `clear` would be better to remove all entries. A `remove` method could be used removing for individual entries. Having separate individual methods is a cleaner design (single responsibility principle).

2022-05-29 08:53 UTC, garethj2 commented on src/util/memoize.ts
> +	public expire(name?: string): void {
I'm worried about clashes between the keys and the method on the prototype chain. 

For example, let's say at some point that a key called `expire` was added that could accidently override the method.

I think it would be better to have the cache data held internally in another object.

    class Cache {
        #cache: Record<string, any> = {}
        ...

2022-05-29 08:53 UTC, garethj2 commented on src/util/memoize.ts
> +	 * (instance as MemoizedObject).$memoizeCache.expire('memoizedElementName')
I don't think we should encourage developers to access a cache via `$memoizeCache`.

Instead it would be super nice to have an exported method called `getMemoizeCache` that can look up and return the cache object or undefined if it can't be found. 

    // Return the cache from `this`. This gives us more flexibility in the future when we might change how the 
    // cache is stored.
    const cache = getMemoizeCache(this)

2022-05-29 22:30 UTC, EliteScientist commented on src/util/memoize.ts
> +	public expire(name?: string): void {
What do you think of this latest change? using a Map as #cache ?

2022-05-30 06:24 UTC, EliteScientist commented on src/util/memoize.ts
> +	public expire(name?: string): void {
Also I kept it in a class instead of just using a Map for future flexibility such as automatically expiring by time and etc...

2022-06-06 07:44 UTC, garethj2 commented on src/util/memoize.ts
> +	public expire(name?: string): void {
Yes I think an internal Map is fine. I don't really mind either way.

2022-06-06 07:47 UTC, garethj2 commented on src/util/memoize.ts
> +	 * (instance as MemoizedObject).$memoizeCache.expire('memoizedElementName')
I was actually thinking of aan exported function that gets you the cache as so...

    @memoize()
    function getValue() {
        const cache = getMemoizeCache()
        // Do something with the cache
    }

The function would use the `this` context inside `getMemoizeCache()` to look up and return the cache instead.

2022-06-06 09:48 UTC, garethj2 commented on src/util/memoize.ts
> +	 * (instance as MemoizedObject).$memoizeCache.expire('memoizedElementName')
@EliteScientist I've added some further code changes into this PR.

2022-06-06 16:18 UTC, merged